-- AlterTable
ALTER TABLE "Badge" ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "courseFinderData" JSONB;
ALTER TABLE "User" ALTER COLUMN "dailyGoal" SET DEFAULT 100;
